# Generated by Django 3.0.6 on 2020-07-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0002_pdb_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdbproperty',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pdbdb.Property'),
        ),
        migrations.AlterField(
            model_name='residueproperty',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pdbdb.Property'),
        ),
    ]
