# Generated by Django 3.0.6 on 2020-07-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0003_auto_20200713_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbproperty',
            name='value_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertytag',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='pdbdb.Property'),
        ),
    ]
