# Generated by Django 3.0.6 on 2020-07-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0005_auto_20200715_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbresidueset',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
