version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=sndgr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /tmp/sndgr:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    build: ./webapp/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sndgr
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - "8000:8000"
    depends_on:
      - db
