FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  # dependencies for building Python packages
  && apt-get install -y build-essential  \
  # psycopg2 dependencies
  && apt-get install -y libpq-dev \
  # Other dependencies
  && apt-get install -y gettext wget curl nano mafft ncbi-blast+ \
  # cleaning up unused files
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /celery
WORKDIR /celery
COPY . .

RUN pip install --no-cache-dir -r requirements/production.txt
CMD ["celery", "-A", "config", "worker", "-l", "INFO"]






