FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  # dependencies for building Python packages
  && apt-get install -y build-essential  \
  # psycopg2 dependencies
  && apt-get install -y libpq-dev \
  # Other dependencies
  && apt-get install -y gettext wget curl nano \
  # cleaning up unused files
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app/
ENV algo 1
COPY . .

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
RUN bash -c 'source $HOME/.bashrc && nvm install 14.16.0 && nvm use v14.16.0 && npm install'
# Fix compatibility issues
RUN sed -i 's|require("bootstrap/js/tooltip.js")|require("bootstrap/js/dist/tooltip.js")|' ./node_modules/feature-viewer/lib/index.js
RUN sed -i 's|require("bootstrap/js/popover.js")|require("bootstrap/js/dist/popover.js")|' ./node_modules/feature-viewer/lib/index.js
RUN sed -i 's|// FIX scrollbars on Mac||' ./node_modules/msa/css/msa.css
############################################################

RUN bash -c 'source $HOME/.bashrc && nvm use v14.16.0 &&  npm run-script build'

RUN pip install --no-cache-dir -r requirements/production.txt
EXPOSE 8000
CMD ["gunicorn", "config.wsgi", "0:8000"]



