# Generated by Django 3.0.6 on 2020-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBx',
            fields=[
                ('dbx_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('url_template', models.TextField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
