# Generated by Django 3.0.6 on 2020-05-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0002_dbx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seqfeature',
            index=models.Index(fields=['bioentry'], name='seqfeature_bioentr_0798ce_idx'),
        ),
        migrations.AddIndex(
            model_name='seqfeature',
            index=models.Index(fields=['type_term'], name='seqfeature_type_te_08e42a_idx'),
        ),
    ]
