# Generated by Django 3.0.6 on 2020-05-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0003_auto_20200523_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioentrydbxref',
            name='dbxref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dbxrefs', to='bioseq.Dbxref'),
        ),
        migrations.AddIndex(
            model_name='bioentrydbxref',
            index=models.Index(fields=['bioentry'], name='bioentry_db_bioentr_3fd652_idx'),
        ),
    ]
