# Generated by Django 3.0.6 on 2020-06-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0005_samplevariant_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='bioentry_id',
            new_name='bioentry',
        ),
    ]
