# Generated by Django 3.0.6 on 2020-06-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0006_auto_20200610_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplevariant',
            old_name='variant_id',
            new_name='variant',
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('bioentry_id', 'pos', 'ref')},
        ),
    ]
