# Generated by Django 3.0.6 on 2020-06-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0007_auto_20200610_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplevariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variants', to='bioseq.Variant'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('gisid', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'samples',
                'managed': True,
                'unique_together': {('name', 'gisid')},
            },
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bioseq.Sample'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='samplevariant',
            unique_together={('variant_id', 'sample_id', 'alt')},
        ),
        migrations.RemoveField(
            model_name='samplevariant',
            name='name',
        ),
    ]
