# Generated by Django 3.0.6 on 2020-06-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0008_auto_20200626_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplevariant',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bioseq.Sample'),
        ),
    ]
