# Generated by Django 3.0.6 on 2020-06-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0009_auto_20200626_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='gisid',
            new_name='gisaid',
        ),
    ]
