# Generated by Django 3.0.6 on 2020-07-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0003_auto_20200713_1709'),
        ('bioseq', '0010_auto_20200626_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdb_variants', to='pdbdb.Residue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdb_variants', to='bioseq.Variant')),
            ],
            options={
                'db_table': 'pdbvariant',
                'managed': True,
            },
        ),
    ]
