# Generated by Django 3.1.4 on 2021-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0011_pdbvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='subdivision',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
