# Generated by Django 3.1.4 on 2021-03-21 02:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sndg_covid19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='status',
            field=models.CharField(default='iniciado', max_length=255),
        ),
        migrations.AddField(
            model_name='importjob',
            name='status_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='csv',
            field=models.FileField(help_text='archivo de propiedades .csv', storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/eze/workspace/covid19-web/uploads'), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='fasta',
            field=models.FileField(help_text='archivo de secuencias en formato .fasta.zip', storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/eze/workspace/covid19-web/uploads'), upload_to='uploads/'),
        ),
    ]
