# Generated by Django 3.1.4 on 2021-03-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sndg_covid19', '0002_auto_20210320_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status_desc',
            field=models.TextField(default=''),
        ),
    ]
