# Generated by Django 3.1.4 on 2021-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sndg_covid19', '0003_auto_20210322_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='debug_status_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='errors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status_desc',
            field=models.TextField(null=True),
        ),
    ]
